### ISSUE TITLE
August 4, 2023 Lab Cleanup

### ISSUE THREAD

**Issue by moorepants** [mechmotum/mechmotum.github.io#126]
- [ ] Obtain all loaned items, review loaned checkout sheet, replenish sheets, update.
- [ ] Batteries
  - [x] Make a common location for all batteries
  - [ ] Ensure all chargers are labeled to match what they charge.
  - [ ] Make a battery charging "last charge" chart so that we can record when batteries/bikes were last charged.
- [x] Cabinets
  - [x] Get rid of any old items we no longer need.
  - [x] Purchase plastic tubs for projects.
  - [x] Make space for temp project storage (entire small cabinet or part of one of the larger cabinets)
  - [x] Organize common materials in cabinets and (re-)label shelves.
  - [x] Consolidate and organize all electronics in cabinets (except for things for electronics bench)
- [x] Electronics table
  - [x] Designate one table as an electronics workbench.
  - [x] Put all useful electronic components, soldering irons, oscilliscope, power supply, etc. on the table. 
  - [x] Attach new metal shelving unit to the elecctronics table for electronic storage above the table.
  - [x] Sort all electronic components and label them on the lab bench (wire, diodes, resistors, sensor chips, etc)
- [x] Labeling
  - [x] Label all bike lab property with the paint pens for permanent markings.
  - [x] Label things that can take a paint pen with the label maker.
- [x] Keys
  - [x] Remove homeless keys from the bicycle key box.
  - [x]  Label all keys for current bikes.
  - [x] Buy more label keychains
  - [x]  Make sure bikes are locked in the basement.
  - [x] Hang key box in the lab.
- [ ] Basement
  - [x] Make sure all bike lab stuff is labeled.
  - [x]  Get rid of excess bicycle rims and tires (stacked beside the floor bicycle rack)
    - All unwanted bicycle wheels (without tires) were placed beside the scrap material bins. All wanted rims were placed beside the bicycles in the hanging bike rack. Tires (to keep) were placed on the shelves and by the kept wheels.
  - [ ] Label the fall mats in the basement with "bicycle lab"
  - [ ] Get rid of skeleton and related materials in the basement (ask Frans van der Helm if he wants it).
  - [x] Move Gabriele's bicycle tires to the basement (could also get rid of ones we don't need)
  - [x] Make storage location for the kickplate and its ramps
  - [x] Break down Georgios's static bicycle measurement structure. Store tubes and connectors in the shelves.
  - [x] Disassemble custom steel bikes and move to metal recycling.
- [ ]  Develop an inventory list of things that are 250 EUR or greater in price (spreadsheet in the shared GDrive)
- [ ] Get rid of bicycles that are no longer needed.
  - [x] Place bicycles that are candidates for removal in the floor rack.
  - [ ] Photograph all bicycles that we'd like to sell or trash.
  - [ ] Investigate options for selling bicycles (can we issue a TUD invoice to a buyer?) or just sell on Maarkplaats?
  - [x] Place all bicycles we definitely will keep in the ceiling rack (or that room).
- [x] Find/make a parking spot for the lab bakfiets.
- [ ] Label the lab bakfiets.
- [ ] Go through all boxes in basement, extract useful stuff, get rid of rest.
  - We did about half of these boxes, still need to sift through the rest.
- [x] Purchase extension cord for the treadmill.
- [x] Install a high power extension cord on the treadmill.
- [x] Purchase floor cord covers.
- [x] Setup power strips at workstations and also floor cord covers 
- [ ] Order new treadmill belt
- [x] Setup (mount) the server in the bike lab (needs GUI based ubuntu LTS installed and to use Jason's netid for ethernet).
- [ ] Repair the treadmill controller.

**Comment by GabrieleDello** [comment]
Ongoing "problem": find a location for kick-plate

**Comment by moorepants** [comment]
Closing and moving remaining issues to:

- #130
- #131
- #132
- #133
- #134
- #135
- #136
- #137
