### ISSUE TITLE
Editing guide error: Missing "env"

### ISSUE THREAD

**Issue by chrismo-schmidt** [mechmotum/mechmotum.github.io#142]
[The command to create a conda environment](https://github.com/mechmotum/mechmotum.github.io/blob/e9e4f4d2631c1b5f7cf296615ecb77274d794216/README.rst?plain=1#L67) for building the website locally misses the "env". It should be:

`conda env create -f env.yml`

**Comment by moorepants** [comment]
Oops, I fixed it before I saw you self assign.

**Comment by chrismo-schmidt** [comment]
Perfect!
