### ISSUE TITLE
Lab cleanup and organization

### ISSUE THREAD

**Issue by moorepants** [mechmotum/mechmotum.github.io#88]
- [ ] get new monitors for the lab
- [ ] make a student project cabinet(s), flexible space where new students can claim a shelf and add their label
- [ ] organize the tools in the tool cabinets, use dividers, bins, labels, and other organizational methods
- [ ] sort all nuts, bolts, things in the plastic bins with labels
- [ ] make 6 workstations
- [ ] remove all raw materials to basement in organized fashion, make at least one raw material shelf that is labeled
- [ ] get rid bad bicycle rims and tires in the basement (probably metal recycling and trash for tires -> talk to Jan v. F.)
- [ ] fold up the mock hexapod bike and store in basement (make sure it can be reassembled with instructions)
- [ ] hang interesting bikes on the wall (talk to Jan v. F. for permissions required)
- [ ] move all bicycles to the basement that are not in active use in the lab or up there for display/demo purposes
- [ ] hang tools on the toolboard (label or make a silhouette of the tool so they end up back in right spot)
- [ ] clear old junk from all cabinets to make space

**Comment by Flaab123** [comment]
@moorepants can you assign me to this issue?
I can't assign myself and I'm therefore unable to edit/complete the task list...
I think I might need write permissions for the repository

**Comment by moorepants** [comment]
Can you edit now?

**Comment by Flaab123** [comment]
I'm assigned to the issue, but I'm still unable to edit the task list unfortunately..

**Comment by moorepants** [comment]
Ok, I need to add you to the org.

**Comment by Flaab123** [comment]
Thanks, but I'm still not able to edit your task list (maybe because it's in a reply from you?).
If you are in the lab tomorrow, maybe we could have a brief look at it.
