### ISSUE TITLE
Lab clean up and organisation

### ISSUE THREAD

**Issue by Flaab123** [mechmotum/mechmotum.github.io#89]
* [x]  sort all nuts, bolts, things in the plastic bins with labels
* [x]  Get new monitors (and HDMI/DP adapters) [there is an open request for this with the secretaries]
* [x]  make 6 workstations
* [ ]  Get rid of excess bicycle rims and tires (stacked beside the floor bicycle rack)
* [x]  hang interesting bikes on the wall (talk to Jan v. F. for permissions required)
* [x]  remove all raw materials to basement in organized fashion, make at least one raw material shelf that is labeled
* [x]  organize the tools in the tool cabinets, use dividers, bins, labels, and other organizational methods
* [x]  move all bicycles to the basement that are not in active use in the lab or up there for display/demo purposes
* [x] send some unneeded bicycles to the kringloopwinkel
* [x] inventory all the bicycles in a spreadsheet
* [x]  make a student project cabinet(s), flexible space where new students can claim a shelf and add their label
* [x]  fold up the mock hexapod bike and store in basement (make sure it can be reassembled with instructions)
* [x]  hang tools on the toolboard (label or make a silhouette of the tool so they end up back in right spot)
* [x]  clear old junk from all cabinets to make space
* [x] setup method for checking out tools from the lab (for lab members that need to use the tools outside the lab or for other labs borrowing our equipment)
* [x] Make space for the large treadmill (likley move cabinets)
* [x] organize all cabinets, shelfs, drawers, etc. with labels and such
* [x] Utilize the small parts bins for organization
* [ ] Develop an inventory list of things that are 250 EUR or greater in price (spreadsheet in the shared GDrive)
* [x] Install a lab equipment check out list on the wall by the door
* [ ] Get rid of the excess bicycles in the basement (all of the ones grouped in the floor rack).
* [x] Organize and label shelves in the basement.
* [x] Move materials under the workbench to the material shelf in the basement.
* [ ] Remove homeless keys from the bicycle key box. Label all keys for current bikes. Make sure bikes are locked in the basement.
* [x] Move the large treadmill into the bicycle lab.
* [ ] Label the fall mats in the basement with "bicycle lab"
* [ ] Dismantle the ice skate measuring device and store the materials in the rack in the basement
* [x] Get rid of the walking treadmill (or service it)
* [ ] Order a broom

**Comment by Flaab123** [comment]
Bicycle rims & tires are sorted. Marked some of the stock as junk which is ready to be reviewed by Arend or Jason

**Comment by moorepants** [comment]
Can you add the new bicycles from Marco and Shannon's project to the bicycle inventory spreadsheet?

**Comment by moorepants** [comment]
> Bicycle rims & tires are sorted. Marked some of the stock as junk which is ready to be reviewed by Arend or Jason

Ok, I'll have a look soon.

**Comment by Flaab123** [comment]
> > Bicycle rims & tires are sorted. Marked some of the stock as junk which is ready to be reviewed by Arend or Jason
> 
> Ok, I'll have a look soon.

Let me know when you want to have a look, because there might be some things worth discussing about what's currently stored. (especially the fact that there are loads of rims and tires of one size that are in a good state)

**Comment by Flaab123** [comment]
I've made requests for monitors (by email) and for the permission to install bicycle mounts on the wall (with a Topdesk call)

**Comment by sdrauksas** [comment]
> Get new monitors (and HDMI/DP adapters) [there is an open request for this with the secretaries]

Four new monitors have arrived! Now we have:
- 3x monitors with DisplayPort, VGA, and DVI-D connectors
- 1x monitor with VGA and DVI-D connectors
- 4x monitors with DisplayPort and HDMI connectors.

When it comes to cables:
- 4x VGA cables (for the old monitors)
- 5x DisplayPort cables (4 new + 1 for the lab's workstation)
- 1x HDMI cable
- 1x white VGA - miniDisplayPort adapter (possibly Jan's personal)
- 1x black VGA - HDMI adapter (Marcos's or Shannon's personal ones?)

> make a student project cabinet(s), flexible space where new students can claim a shelf and add their label

The cabinets have been cleared out and there is quite some free space, I saw Tim has already claimed a part of one shelf. So if anyone needs cabinet space for their projects - feel free to grab some.

> organize all cabinets, shelfs, drawers, etc. with labels and such
> Utilize the small parts bins for organization

We now have a shelf dedicated to electronics (with labeled boxes), a shelf dedicated to safety equipment (helmets, harness, pads) and a few other miscellaneous labelled places. Feel free to label more stuff

**Comment by moorepants** [comment]
I checked off the relevant solved items. Thanks!

**Comment by moorepants** [comment]
Most things were taken care of here. Opening #126 for the 2023 lab cleanup.
